#!/bin/sh

export LC_ALL=en_US.UTF-8
export POSIXLY_CORRECT=yes

print_help() {
    echo "Usage: tradelog [-h|--help] [FILTER] [COMMAND] [LOG [LOG2 [...]]"
    echo ""
    echo "COMMAND"
    echo "  list-tick   Prints a list of occurring stock symbols"
    echo "  profit      Overall profit"
    echo "  pos         Value of held stock symbol"
    echo "  last-price  Last known price of each ticker"
    echo "  hist-ord    Transactions history of ticker"
    echo "  graph-pos   Graph of values of held positions according to ticker"
    echo ""
    echo "FILTER"
    echo "  -a DATETIME     after - uses tickers after set time"
    echo "  -b DATETIME     before - uses tickers before set time"
    echo "  -t TICKER       uses only selected tickers"
    echo "  -w WIDTH        Width of the longest line in graph"
    echo "  -h --help       help"
}

BEFORE="9999-99-99"
# parsing parameters
while [ "$#" -gt 0 ]; do
    case "$1" in
    -h | --help)
        print_help
        exit 0
        ;;
    list-tick)
        COMMAND="list-tick"
        shift
        ;;
    profit)
        COMMAND="profit"
        shift
        ;;
    pos)
        COMMAND="pos"
        shift
        ;;    
    last-price)
        COMMAND="last-price"
        shift
        ;;
    hist-ord)
        COMMAND="hist-ord"
        shift
        ;;
    graph-pos)
        COMMAND="graph-pos"
        shift
        ;;
    -t)
        TICKERS="$2\|$TICKERS"
        shift; shift
        ;;
    -b)
        BEFORE="$2"
        shift; shift
        ;;
    -a)
        AFTER="$2"
        shift; shift
        ;;
    -w)
        if [ ! -z "$WIDTH" ]; then
            1>&2 echo "Only one WIDTH parameter allowed"
            exit 1
        fi
        WIDTH="$2"
        if [ "$WIDTH" -le 0 ]; then
            1>&2 echo "Invalid WIDTH parameter"
            exit 1
        fi
        shift; shift
        ;;
    *)
        if [ ! -f "$1" ]; then
           1>&2 echo "$1 is not a file or parameter"
           exit 1
        fi
        
        if [ $1 == *".gz" ]; then
            LOG_GZ="$LOG_GZ $1"
        else
            LOG="$LOG $1"
        fi
        shift
        ;;
    esac
done

# Parsing inputs
# Only raw text or stdin
READ_INPUT="cat $LOG"
# gz and raw text
if [ "$LOG_GZ" ] && [ "$LOG" ]; then
    READ_INPUT+=" && gzip -d -c $LOG_GZ"
# only gz
elif [ "$LOG_GZ" ] && [ !"$LOG" ]; then
    READ_INPUT="gzip -d -c $LOG_GZ"
fi

FILTER="eval $READ_INPUT"
# FILTERS
if [ "$TICKERS" ]; then
    FILTER="$FILTER | grep -w \$TICKERS"
fi
if [ "$AFTER" ]; then
    FILTER="$FILTER | awk -F ';' '\$1 > \"$AFTER\" {print \$0}'"
fi
if [ "$BEFORE" != "9999-99-99" ]; then
    FILTER="$FILTER | awk -F ';' '\$1 < \"$BEFORE\" {print \$0}'"
fi

#Sorts output for last-price and pos
SORTER="eval awk -F ':' '{ print length(\$2), \$0 }' | sort -n -r | cut -d\" \" -f2- | 
    awk -F ':' '{ if(len == \"\")len = length(\$2); printf(\"%-10s: %*s\n\", \$1, len, \$2)}'"

# Execute
case "$COMMAND" in
    list-tick)
        $FILTER | awk -F ';' '{print $2}' | sort -u
        ;;
    profit)
        $FILTER | awk -F ';' '{if ($3 == "buy") {sum-=$4*$6}
                        else {sum+=$4*$6}} END {printf "%.2f\n", sum}'
        ;;
    pos)
        # Sort chronologically and by TICKERS
        FILTER="$FILTER | sort -s -t ';' -k 2,2"
        $FILTER | awk -F ';' '{ 
            # first line
            if (curTick == "") {
                curTick = $2
                sum = 0
            }
            # new ticker                            
            else if (curTick != $2) {
                printf("%s:%.2f\n", curTick, sum*lastPrice)
                curTick = $2
                sum = 0
            }            
            # sum money
            if ($3 == "buy")
                sum+=$6
            else 
                sum-=$6

            lastPrice = $4
        } END {printf("%s:%.2f\n", curTick, sum*lastPrice)}' | $SORTER | sort -t ':' -k 2,2 -n -r
        ;;
    last-price)
        FILTER="$FILTER | sort -s -t ';' -k 2,2"
            $FILTER | awk -F ';' '{
            if (curTick == "") {
                curTick = $2
            }
            # new ticker                            
            if (curTick != $2) {
                printf("%s:%.2f\n", curTick, lastPrice)
                curTick = $2
            }
            lastPrice = $4
        } END {printf("%s:%.2f\n", curTick, lastPrice)}' | $SORTER | sort -t ':' -k 1,1
        ;;
    hist-ord)
        FILTER="$FILTER | sort -s -t ';' -k 2,2"
        $FILTER | awk -F ';' '{ 
            # first line
            if (curTick == "") {
                curTick = $2
                transact = 0
            }
            # new ticker                            
            else if (curTick != $2) {
                printf("%-10s: ", curTick)
                for (i=0; i<transact; i++){printf("#")}
                printf("\n")
                curTick = $2
                transact = 0
            }            
            # sum transactions
            transact+=1
        } END {printf("%-10s: ", curTick);for (i=0; i<transact; i++){printf("#")};printf("\n")}'
        ;;
    *)
        $FILTER
esac

exit 0
